/// The test that should have existed first.
///
/// Every bug this app has shipped came through the same hole: `src/backend.ts`
/// had no test at all, and the 103 tests that did exist ran against
/// `dev/mock.ts` — a mock written by the same hand, holding the same wrong
/// belief. A mock cannot falsify the assumption it was built from. Four
/// separate wire bugs passed a green suite:
///
///   1. `createCanisterClient().call()`, an API the SDK never had
///   2. `()` sent as `[]` instead of `[null]`
///   3. `Nat`/`Int` treated as bigint rather than decimal string
///   4. `?T` treated as `[]`/`[value]` rather than absent-or-bare
///   5. a Motoko tuple `(a, b)` sent as two arguments instead of one
///
/// So this file does not ask the mock anything. It asks `dist/schema.json` —
/// the Candid schema generated from the backend by the packaging pipeline,
/// which is the same artifact the kernel validates against at runtime. The SDK
/// is replaced by a recorder, every client function is driven once, and what it
/// tried to send is checked against the schema for that method.
///
/// Replies are synthesised from each method's *output* schema, so the decoders
/// are exercised against schema-conformant data rather than against the mock's
/// idea of it. Each method is driven twice: once with every optional field
/// present, once with only the required ones, because an absent optional is
/// omitted from the record entirely and that is what broke the oracle page.

import { beforeAll, describe, expect, mock, test } from "bun:test";
import { readFileSync } from "node:fs";

type Schema = Record<string, any>;

// Read synchronously: bun collects `describe` blocks during the synchronous
// evaluation of this module, so a top-level `await` here registers nothing.
const SCHEMA_PATH = new URL("../dist/schema.json", import.meta.url);

/// Generated by `npm run schema`, and committed, because it is the wire
/// contract rather than a build leftover: a change to it is a change to what
/// the canister will accept, and that belongs in a diff someone reads.
function loadSchema(): Schema | null {
  try {
    return JSON.parse(readFileSync(SCHEMA_PATH, "utf8"));
  } catch {
    return null;
  }
}

const schema: Schema | null = loadSchema();

if (schema === null) {
  // Never skip quietly. A green suite that silently stopped checking the wire
  // is the exact condition that let five encoding bugs ship.
  test("dist/schema.json is present", () => {
    throw new Error(
      "dist/schema.json is missing, so the wire contract went unchecked. " +
        "Run `npm run schema` (or `npm run package`) and re-run the tests.",
    );
  });
}

// --------------------------------------------------------------- validation

/// The generated schema uses a small, fixed slice of JSON Schema: object with
/// `properties`/`required`/`additionalProperties`, array with either
/// `prefixItems` (a tuple) or `items` (a vector), the scalar types, and `oneOf`
/// for a variant. That is the whole vocabulary, so this is the whole validator.
function validate(value: unknown, s: Schema, path = "$"): string[] {
  if (s.oneOf) {
    const tries = s.oneOf.map((branch: Schema) => validate(value, branch, path));
    return tries.some((errs: string[]) => errs.length === 0)
      ? []
      : [`${path}: matched none of the ${s.oneOf.length} variant arms`];
  }
  switch (s.type) {
    case "object": {
      if (typeof value !== "object" || value === null || Array.isArray(value)) {
        return [`${path}: expected an object, got ${shapeOf(value)}`];
      }
      const v = value as Record<string, unknown>;
      const errs: string[] = [];
      for (const key of s.required ?? []) {
        if (!Object.hasOwn(v, key)) errs.push(`${path}.${key}: required, absent`);
      }
      for (const key of Object.keys(v)) {
        const child = s.properties?.[key];
        if (!child) {
          if (s.additionalProperties === false) {
            errs.push(`${path}.${key}: not a field of this record`);
          }
          continue;
        }
        errs.push(...validate(v[key], child, `${path}.${key}`));
      }
      return errs;
    }
    case "array": {
      if (!Array.isArray(value)) {
        return [`${path}: expected an array, got ${shapeOf(value)}`];
      }
      if (s.prefixItems) {
        const errs: string[] = [];
        if (typeof s.minItems === "number" && value.length < s.minItems) {
          errs.push(`${path}: expected at least ${s.minItems} items, got ${value.length}`);
        }
        if (typeof s.maxItems === "number" && value.length > s.maxItems) {
          errs.push(`${path}: expected at most ${s.maxItems} items, got ${value.length}`);
        }
        s.prefixItems.forEach((child: Schema, i: number) => {
          if (i < value.length) errs.push(...validate(value[i], child, `${path}[${i}]`));
        });
        return errs;
      }
      return value.flatMap((entry, i) =>
        s.items ? validate(entry, s.items, `${path}[${i}]`) : [],
      );
    }
    case "string":
      return typeof value === "string"
        ? []
        : [`${path}: expected a string${s.description ? ` (${s.description})` : ""}, got ${shapeOf(value)}`];
    case "boolean":
      return typeof value === "boolean" ? [] : [`${path}: expected a boolean, got ${shapeOf(value)}`];
    case "null":
      return value === null ? [] : [`${path}: expected null, got ${shapeOf(value)}`];
    default:
      return [];
  }
}

function shapeOf(value: unknown): string {
  if (value === null) return "null";
  if (Array.isArray(value)) return `an array of ${value.length}`;
  if (typeof value === "bigint") return `a bigint (${value})`;
  return `a ${typeof value}${typeof value === "number" ? ` (${value})` : ""}`;
}

// ----------------------------------------------------------------- fixtures

/// A value the schema would accept. `full` decides whether optional fields —
/// the ones absent from `required` — are present or omitted.
function sample(s: Schema, full: boolean): unknown {
  if (s.oneOf) return sample(s.oneOf[0], full);
  switch (s.type) {
    case "object": {
      const out: Record<string, unknown> = {};
      const required: string[] = s.required ?? [];
      for (const [key, child] of Object.entries(s.properties ?? {})) {
        if (!full && !required.includes(key)) continue;
        out[key] = sample(child as Schema, full);
      }
      return out;
    }
    case "array":
      if (s.prefixItems) return s.prefixItems.map((c: Schema) => sample(c, full));
      return s.items ? [sample(s.items, full)] : [];
    case "string":
      // "bigint as string" is the schema's own wording for Nat and Int.
      return s.description?.includes("bigint") ? "7" : "x";
    case "boolean":
      return false;
    case "null":
      return null;
    default:
      return null;
  }
}

// ------------------------------------------------------------ the recorder

type Sent = { method: string; args: unknown[] };
const sent: Sent[] = [];
let fullReplies = true;

function record(method: string, args: unknown[]): Promise<unknown> {
  sent.push({ method, args });
  const thrown = (globalThis as any).__wireThrow;
  if (thrown !== undefined) return Promise.reject(thrown);
  const canned = (globalThis as any).__wireReply;
  if (canned !== undefined) return Promise.resolve(canned);
  const out = schema!.methods[method]?.output;
  return Promise.resolve(out === undefined ? null : sample(out, fullReplies));
}

mock.module("neutron-tools/app", () => ({
  querySelf: (method: string, args: unknown[] = []) => record(method, args),
  updateSelf: (method: string, args: unknown[] = []) => record(method, args),
  callCanisterDialog: () => Promise.resolve(null),
  loadNeutronCanisterId: () => Promise.resolve("aaaaa-aa"),
}));

// Statically importing would hoist above `mock.module` and defeat it, so the
// client is pulled in once the recorder is registered.
let backend: typeof import("./backend");
beforeAll(async () => {
  backend = await import("./backend");
});

const card = { cardIndex: 3, reversed: true, position: "past" };

/// One entry per method the client can call. `run` must exercise exactly the
/// method it names.
const CALLS: { method: string; run: () => Promise<unknown> }[] = [
  { method: "journal", run: () => backend.loadJournal(true) },
  { method: "history", run: () => backend.loadReadings() },
  { method: "consult", run: () => backend.consultOracle("a question") },
  { method: "seal", run: () => backend.seal({ readingId: 1, movingLines: 2, kameaOrder: 5, cards: [card] }) },
  { method: "save_draw", run: () => backend.saveDraw({ movingLines: 2, cards: [card] }) },
  { method: "save_sigil", run: () => backend.saveSigil({ phrase: "a phrase", movingLines: 3, overridden: true }) },
  { method: "set_note", run: () => backend.setNote("draw-1", "a note") },
  { method: "delete_entry", run: () => backend.deleteEntry("draw-1") },
  { method: "shuffle_deck", run: () => backend.shuffleDeck("seed") },
  { method: "advance_deck", run: () => backend.advanceDeck(3) },
  { method: "set_entered", run: () => backend.setEntered() },
  { method: "set_place", run: () => backend.setPlace("Kyoto") },
  { method: "set_theme", run: () => backend.setTheme("dark") },
  { method: "clear", run: () => backend.clearAll() },
];

describe.if(schema !== null)("what the client sends matches the generated schema", () => {
  for (const { method, run } of CALLS) {
    test(method, async () => {
      sent.length = 0;
      await run();

      const call = sent.find((c) => c.method === method);
      expect(call, `${method} was never sent`).toBeDefined();

      const input = schema!.methods[method]?.input;
      expect(input, `${method} is not in dist/schema.json`).toBeDefined();

      const errs = validate(call!.args, input, `${method}.args`);
      expect(errs.join("\n")).toBe("");
    });
  }
});

describe.if(schema !== null)("every method takes exactly one top-level argument", () => {
  // Motoko arity is the trap this codifies. A declared input of `(a, b)` is a
  // tuple, and a tuple is one value: it crosses as `[[a, b]]`. A one-element
  // tuple `(a)` is just `a`. Sending `[a, b]` is the wrong arity and the call
  // is refused — which is what broke the Tarot page's `save_draw`.
  for (const { method, run } of CALLS) {
    test(method, async () => {
      sent.length = 0;
      await run();
      const call = sent.find((c) => c.method === method)!;
      expect(call.args.length).toBe(1);

      const inner = schema!.methods[method].input.prefixItems[0];
      if (inner.prefixItems) {
        expect(Array.isArray(call.args[0])).toBe(true);
        expect((call.args[0] as unknown[]).length).toBe(inner.prefixItems.length);
      }
    });
  }
});

describe.if(schema !== null)("no Nat or Int is ever sent as a number or a bigint", () => {
  // The kernel stringifies a bigint on the way out (`candidate.toString(10)`),
  // so everything numeric arrives as a decimal string and must leave as one.
  for (const { method, run } of CALLS) {
    test(method, async () => {
      sent.length = 0;
      await run();
      const call = sent.find((c) => c.method === method)!;
      const offenders: string[] = [];
      const walk = (v: unknown, path: string) => {
        if (typeof v === "bigint") offenders.push(`${path} is a bigint`);
        else if (typeof v === "number") offenders.push(`${path} is a number (${v})`);
        else if (Array.isArray(v)) v.forEach((e, i) => walk(e, `${path}[${i}]`));
        else if (v && typeof v === "object") {
          for (const [k, e] of Object.entries(v)) walk(e, `${path}.${k}`);
        }
      };
      walk(call.args, method);
      expect(offenders.join("\n")).toBe("");
    });
  }
});

describe("a refusal survives as data, not as a thrown error", () => {
  // The canister answers `{#reading; #refused}`. Those names are chosen so the
  // kernel does NOT apply its ok/err special case, which returns `ok` bare and
  // throws `err` — the SDK then wraps the throw in an Error, and a deliberate
  // refusal becomes indistinguishable from a dead canister.
  test("a reading arrives as { ok }", async () => {
    (globalThis as any).__wireReply = { reading: { id: "1" } };
    try {
      const result = await backend.consultOracle("a question");
      expect("ok" in result).toBe(true);
      expect((result as { ok: any }).ok.id).toBe("1");
    } finally {
      delete (globalThis as any).__wireReply;
    }
  });

  test("a refusal arrives as { err }, with its reason intact", async () => {
    (globalThis as any).__wireReply = { refused: "Ask a question first." };
    try {
      const result = await backend.consultOracle("");
      expect("err" in result).toBe(true);
      expect((result as { err: string }).err).toBe("Ask a question first.");
    } finally {
      delete (globalThis as any).__wireReply;
    }
  });

  test("a transport failure still rejects", async () => {
    // The SDK wraps every rejection in an Error (neutron-tools `toError`), so
    // this is the only shape a real failure ever takes.
    (globalThis as any).__wireThrow = new Error("the canister is stopped");
    try {
      await expect(backend.consultOracle("q")).rejects.toThrow("the canister is stopped");
    } finally {
      delete (globalThis as any).__wireThrow;
    }
  });
});

describe.if(schema !== null)("replies decode whether or not their optionals are present", () => {
  // A present optional is the bare value; an absent one is omitted from the
  // record. Reading `.length` on the absent case is what made a successful
  // cast report itself as a canister failure.
  for (const present of [true, false]) {
    describe(present ? "optionals present" : "optionals absent", () => {
      for (const { method, run } of CALLS) {
        test(method, async () => {
          fullReplies = present;
          sent.length = 0;
          try {
            await run();
          } finally {
            fullReplies = true;
          }
        });
      }
    });
  }
});
